import { Oswald, Inter } from "next/font/google";
import "./globals.css";

const oswald = Oswald({ subsets: ["latin"], variable: "--font-oswald" });
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata = {
  title: "CineAI",
  description: "Discover the power of AI in cinema with CineAI. Explore movie recommendations, reviews, and insights generated by advanced artificial intelligence algorithms. Enhance your movie-watching experience with personalized suggestions and in-depth analysis.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-black text-zinc-200">
      <body className={`${inter.variable} ${oswald.variable} font-sans antialiased selection:bg-white selection:text-black`}>
        {children}
      </body>
    </html>
  );
}